# Generated by Django 2.1.5 on 2019-10-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191020_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=12)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='report',
            name='lng',
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Location', null=True),
            preserve_default=False,
        ),
    ]
