# Generated by Django 2.1.5 on 2019-10-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191020_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
    ]
